// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify
 * this file See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.seitenbau.jenkins.plugins.dynamicparameter;

public class ChoiceParameterDefinitionParameterBuilder extends
    ChoiceParameterDefinitionParameterBuilderBase<ChoiceParameterDefinitionParameterBuilder>
{
  public static ChoiceParameterDefinitionParameterBuilder choiceParameterDefinitionParameter()
  {
    return new ChoiceParameterDefinitionParameterBuilder();
  }

  public ChoiceParameterDefinitionParameterBuilder()
  {
    super(new ChoiceParameterDefinitionParameter());
  }

  public ChoiceParameterDefinitionParameter build()
  {
    return getInstance();
  }
}

class ChoiceParameterDefinitionParameterBuilderBase<GeneratorT extends ChoiceParameterDefinitionParameterBuilderBase<GeneratorT>>
{
  private ChoiceParameterDefinitionParameter instance;

  protected ChoiceParameterDefinitionParameterBuilderBase(
      ChoiceParameterDefinitionParameter aInstance)
  {
    instance = aInstance;
  }

  protected ChoiceParameterDefinitionParameter getInstance()
  {
    return instance;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withName(String aValue)
  {
    instance.setName(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withScript(String aValue)
  {
    instance.setScript(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withDescription(String aValue)
  {
    instance.setDescription(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withUuid(String aValue)
  {
    instance.setUuid(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withRemote(boolean aValue)
  {
    instance.setRemote(aValue);

    return (GeneratorT) this;
  }
}
