package com.seitenbau.jenkins.plugins.dynamicparameter;

import hudson.FilePath;
import hudson.model.Label;
import hudson.model.ParameterDefinition;
import hudson.model.ParameterValue;
import hudson.model.StringParameterValue;
import hudson.remoting.Callable;
import hudson.remoting.VirtualChannel;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.sf.json.JSONObject;

import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.StringUtils;
import org.kohsuke.stapler.StaplerRequest;

import com.seitenbau.jenkins.plugins.dynamicparameter.scriptler.ScriptlerParameterDefinition;
import com.seitenbau.jenkins.plugins.dynamicparameter.util.JenkinsUtils;

public abstract class BaseParameterDefinition extends ParameterDefinition
{
  /** Serial version UID. */
  private static final long serialVersionUID = -4415132917610378545L;

  /** Logger. */
  protected static final Logger logger = Logger.getLogger(ScriptlerParameterDefinition.class
      .getName());

  /** UUID identifying the current parameter. */
  private final UUID _uuid;

  /** Flag showing if the script should be executed remotely. */
  private final boolean _remote;

  protected BaseParameterDefinition(String name, String description, String uuid, boolean remote)
  {
    super(name, description);
    _remote = remote;

    if (StringUtils.length(uuid) == 0)
    {
      _uuid = UUID.randomUUID();
    }
    else
    {
      _uuid = UUID.fromString(uuid);
    }
  }

  /**
   * Should the script be executed to on a remote slave?
   * @return {@code true} if the script should be executed remotely
   */
  public final boolean isRemote()
  {
    return _remote;
  }

  /**
   * Get unique id for this parameter definition.
   * @return the _uuid
   */
  public final UUID getUUID()
  {
    return _uuid;
  }

  /**
   * Get the script result as a list.
   * @return list of values if the script returns a non-null list;
   *         {@link Collections#EMPTY_LIST}, otherwise
   */
  @SuppressWarnings("unchecked")
  public final List<Object> getScriptResultAsList()
  {
    Object value = getScriptResult();
    if (value instanceof List)
    {
      return (List<Object>) value;
    }
    String name = getName();
    String msg = String.format("Script parameter with name '%s' is not a instance of "
        + "java.util.List the parameter value is : %s", name, value);
    logger.info(msg);
    return Collections.EMPTY_LIST;
  }

  /**
   * Get the script result as a string.
   * @return the default value generated by the script or {@code null}
   */
  public final String getScriptResultAsString()
  {
    Object value = getScriptResult();
    return ObjectUtils.toString(value, null);
  }

  @Override
  public final ParameterValue createValue(StaplerRequest req, JSONObject jo)
  {
    StringParameterValue parameterValue = req.bindJSON(StringParameterValue.class, jo);
    parameterValue.setDescription(getDescription());
    return checkParameterValue(parameterValue);
  }

  @Override
  public final ParameterValue createValue(StaplerRequest req)
  {
    String name = getName();
    String[] values = req.getParameterValues(name);
    return createParameterValue(name, values);
  }

  private ParameterValue createParameterValue(String name, String[] values)
  {
    if (values == null)
    {
      return getDefaultParameterValue();
    }
    else if (values.length == 1)
    {
      StringParameterValue parameterValue = createStringParameterValueFor(name, values[0]);
      return checkParameterValue(parameterValue);
    }
    else
    {
      throw new IllegalArgumentException(String.format(
          "Illegal number of parameter values for '%s': %d", getName(), values.length));
    }
  }

  /**
   * Execute the script and return the result.
   * @return script result or {@code null}
   */
  protected abstract Object getScriptResult();

  /**
   * Checks the validity of the given parameter value.
   * @param value parameter value to check
   * @return if the value is valid the same parameter value
   * @throws IllegalArgumentException if the value in not valid
   */
  protected StringParameterValue checkParameterValue(StringParameterValue value)
  {
    return value;
  }

  protected Object executeScript(Callable<Object, Throwable> call)
  {
    try
    {
      if (isRemote())
      {
        Label label = JenkinsUtils.findProjectLabel(getUUID());
        if (label == null)
        {
          logger.warning(String.format(
            "No label is assigned to project; script for parameter '%s' will be executed on master",
            getName()));
        }
        else
        {
          VirtualChannel channel = JenkinsUtils.findActiveChannel(label);
          if (channel == null)
          {
            logger.warning(String.format(
                "Cannot find an active node of the label '%s' where to execute the script",
                label.getDisplayName()));
          }
          else
          {
            return channel.call(call);
          }
        }
      }
      return call.call();
    }
    catch (Throwable e)
    {
      String msg = String.format("Error during executing script for parameter '%s'", getName());
      logger.log(Level.SEVERE, msg, e);
    }
    return null;
  }

  protected Object generateValue(String script, Map<String, String> parameters)
  {
    ParameterizedScriptCall call = new ParameterizedScriptCall(script, parameters);
    return executeScript(call);
  }

  protected Object generateValue(String script, FilePath[] classPath)
  {
    ClasspathScriptCall call = new ClasspathScriptCall(script, classPath);
    return executeScript(call);
  }

  /**
   * Factory methods creates a String parameter value object for the
   * given value.
   * @param value of the object
   * @return String parameter value object not null.
   */
  private StringParameterValue createStringParameterValueFor(String name, String value)
  {
    String description = getDescription();
    StringParameterValue parameterValue = new StringParameterValue(name, value, description);
    return parameterValue;
  }

  /**
   * Remote call implementation.
   */
  public static final class ParameterizedScriptCall implements Callable<Object, Throwable>
  {
    private static final long serialVersionUID = -8281488869664773282L;

    private final String _remoteScript;

    private final Map<String, String> _parameters;

    /**
     * Constructor.
     * @param script script to execute
     * @param parameters parameters
     */
    public ParameterizedScriptCall(String script, Map<String, String> parameters)
    {
      _remoteScript = script;
      _parameters = parameters;
    }

    @Override
    public Object call()
    {
      return JenkinsUtils.execute(_remoteScript, _parameters);
    }

  }

  /**
   * Remote call implementation.
   */
  public static final class ClasspathScriptCall implements Callable<Object, Throwable>
  {
    private static final long serialVersionUID = -8281488869664773282L;

    private final String _remoteScript;

    private final FilePath[] _classPaths;

    /**
     * Constructor.
     * @param script script to execute
     * @param classPaths class paths
     */
    public ClasspathScriptCall(String script, FilePath[] classPaths)
    {
      _remoteScript = script;
      _classPaths = classPaths;
    }

    @Override
    public Object call()
    {
      return JenkinsUtils.execute(_remoteScript, _classPaths);
    }

  }
}
